[phases.setup]
nixPkgs = ["php82", "composer", "nodejs", "npm", "sqlite", "unzip", "curl"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan migrate --force",
    "php artisan storage:link"
]

[phases.start]
cmds = ["php artisan serve --host=0.0.0.0 --port=${PORT}"]
