[phases.setup]
nixPkgs = ["php81", "composer", "nodejs_18", "npm"]

[phases.build]
cmds = [
  "composer install --no-dev --no-interaction --prefer-dist",
  "npm install && npm run build"
]

[phases.start]
cmds = ["php artisan serve --host=0.0.0.0 --port=$PORT"]
